[secrets] # Fill in Discord Token and API keys from different sites
discord = "TOKEN"
ocrspace = ""
wolframalpha = ""
weatherapi = ""

[bot]
status = "online" # online/idle/dnd/offline
activity_type = "playing" # playing/listening/watching/competing
activity = ""