[secrets] # Fill in Discord Token and API keys from different sites
discord = "TOKEN"
wolframalpha = ""
weatherapi = ""
gcp_ocr = ""
gcp_translate = ""

[bot]
status = "online" # online/idle/dnd/offline
activity_type = "playing" # playing/listening/watching/competing
activity = ""

[misc]
asset_url = "https://raw.githubusercontent.com/Vocaned/Voagel/master/assets/"
